/**
 * This file was auto-generated by @liangskyli/openapi-gen-ts.
 * Do not make direct changes to the file.
 */
import type { paths } from './ts-schema'

export interface IApi {
  '/api/MaaAdbControllerCreate': {
    Body?: NonNullable<
      paths['/api/MaaAdbControllerCreate']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaAdbControllerCreate']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaAdbControllerCreateV2': {
    Body?: NonNullable<
      paths['/api/MaaAdbControllerCreateV2']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaAdbControllerCreateV2']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaBindController': {
    Body?: NonNullable<
      paths['/api/MaaBindController']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaBindController']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaBindResource': {
    Body?: NonNullable<
      paths['/api/MaaBindResource']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaBindResource']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaClearCustomAction': {
    Body?: NonNullable<
      paths['/api/MaaClearCustomAction']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaClearCustomAction']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaClearCustomRecognizer': {
    Body?: NonNullable<
      paths['/api/MaaClearCustomRecognizer']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaClearCustomRecognizer']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaClearImage': {
    Body?: NonNullable<
      paths['/api/MaaClearImage']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaClearImage']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaControllerConnected': {
    Body?: NonNullable<
      paths['/api/MaaControllerConnected']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaControllerConnected']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaControllerDestroy': {
    Body?: NonNullable<
      paths['/api/MaaControllerDestroy']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaControllerDestroy']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaControllerGetImage': {
    Body?: NonNullable<
      paths['/api/MaaControllerGetImage']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaControllerGetImage']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaControllerGetUUID': {
    Body?: NonNullable<
      paths['/api/MaaControllerGetUUID']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaControllerGetUUID']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaControllerPostClick': {
    Body?: NonNullable<
      paths['/api/MaaControllerPostClick']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaControllerPostClick']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaControllerPostConnection': {
    Body?: NonNullable<
      paths['/api/MaaControllerPostConnection']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaControllerPostConnection']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaControllerPostInputText': {
    Body?: NonNullable<
      paths['/api/MaaControllerPostInputText']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaControllerPostInputText']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaControllerPostPressKey': {
    Body?: NonNullable<
      paths['/api/MaaControllerPostPressKey']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaControllerPostPressKey']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaControllerPostScreencap': {
    Body?: NonNullable<
      paths['/api/MaaControllerPostScreencap']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaControllerPostScreencap']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaControllerPostSwipe': {
    Body?: NonNullable<
      paths['/api/MaaControllerPostSwipe']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaControllerPostSwipe']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaControllerPostTouchDown': {
    Body?: NonNullable<
      paths['/api/MaaControllerPostTouchDown']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaControllerPostTouchDown']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaControllerPostTouchMove': {
    Body?: NonNullable<
      paths['/api/MaaControllerPostTouchMove']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaControllerPostTouchMove']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaControllerPostTouchUp': {
    Body?: NonNullable<
      paths['/api/MaaControllerPostTouchUp']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaControllerPostTouchUp']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaControllerSetOptionBoolean': {
    Body?: NonNullable<
      paths['/api/MaaControllerSetOptionBoolean']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaControllerSetOptionBoolean']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaControllerSetOptionInteger': {
    Body?: NonNullable<
      paths['/api/MaaControllerSetOptionInteger']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaControllerSetOptionInteger']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaControllerSetOptionString': {
    Body?: NonNullable<
      paths['/api/MaaControllerSetOptionString']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaControllerSetOptionString']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaControllerStatus': {
    Body?: NonNullable<
      paths['/api/MaaControllerStatus']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaControllerStatus']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaControllerWait': {
    Body?: NonNullable<
      paths['/api/MaaControllerWait']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaControllerWait']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaCreate': {
    Body?: NonNullable<
      paths['/api/MaaCreate']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaCreate']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaCreateImageBuffer': {
    Body?: NonNullable<
      paths['/api/MaaCreateImageBuffer']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaCreateImageBuffer']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaDbgControllerCreate': {
    Body?: NonNullable<
      paths['/api/MaaDbgControllerCreate']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaDbgControllerCreate']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaDestroy': {
    Body?: NonNullable<
      paths['/api/MaaDestroy']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaDestroy']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaDestroyImageBuffer': {
    Body?: NonNullable<
      paths['/api/MaaDestroyImageBuffer']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaDestroyImageBuffer']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaGetController': {
    Body?: NonNullable<
      paths['/api/MaaGetController']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaGetController']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaGetImageEncoded': {
    Body?: NonNullable<
      paths['/api/MaaGetImageEncoded']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaGetImageEncoded']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaGetImageHeight': {
    Body?: NonNullable<
      paths['/api/MaaGetImageHeight']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaGetImageHeight']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaGetImageType': {
    Body?: NonNullable<
      paths['/api/MaaGetImageType']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaGetImageType']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaGetImageWidth': {
    Body?: NonNullable<
      paths['/api/MaaGetImageWidth']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaGetImageWidth']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaGetResource': {
    Body?: NonNullable<
      paths['/api/MaaGetResource']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaGetResource']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaInited': {
    Body?: NonNullable<
      paths['/api/MaaInited']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaInited']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaIsImageEmpty': {
    Body?: NonNullable<
      paths['/api/MaaIsImageEmpty']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaIsImageEmpty']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaPostStop': {
    Body?: NonNullable<
      paths['/api/MaaPostStop']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaPostStop']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaPostTask': {
    Body?: NonNullable<
      paths['/api/MaaPostTask']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaPostTask']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaResourceCreate': {
    Body?: NonNullable<
      paths['/api/MaaResourceCreate']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaResourceCreate']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaResourceDestroy': {
    Body?: NonNullable<
      paths['/api/MaaResourceDestroy']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaResourceDestroy']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaResourceGetHash': {
    Body?: NonNullable<
      paths['/api/MaaResourceGetHash']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaResourceGetHash']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaResourceGetTaskList': {
    Body?: NonNullable<
      paths['/api/MaaResourceGetTaskList']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaResourceGetTaskList']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaResourceLoaded': {
    Body?: NonNullable<
      paths['/api/MaaResourceLoaded']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaResourceLoaded']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaResourcePostPath': {
    Body?: NonNullable<
      paths['/api/MaaResourcePostPath']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaResourcePostPath']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaResourceStatus': {
    Body?: NonNullable<
      paths['/api/MaaResourceStatus']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaResourceStatus']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaResourceWait': {
    Body?: NonNullable<
      paths['/api/MaaResourceWait']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaResourceWait']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaSetGlobalOptionBoolean': {
    Body?: NonNullable<
      paths['/api/MaaSetGlobalOptionBoolean']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaSetGlobalOptionBoolean']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaSetGlobalOptionInteger': {
    Body?: NonNullable<
      paths['/api/MaaSetGlobalOptionInteger']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaSetGlobalOptionInteger']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaSetGlobalOptionString': {
    Body?: NonNullable<
      paths['/api/MaaSetGlobalOptionString']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaSetGlobalOptionString']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaSetImageEncoded': {
    Body?: NonNullable<
      paths['/api/MaaSetImageEncoded']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaSetImageEncoded']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaSetTaskParam': {
    Body?: NonNullable<
      paths['/api/MaaSetTaskParam']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaSetTaskParam']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaStop': {
    Body?: NonNullable<paths['/api/MaaStop']['post']['requestBody']>['content']['application/json']
    Response: paths['/api/MaaStop']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaTaskAllFinished': {
    Body?: NonNullable<
      paths['/api/MaaTaskAllFinished']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaTaskAllFinished']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaTaskStatus': {
    Body?: NonNullable<
      paths['/api/MaaTaskStatus']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaTaskStatus']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaThriftControllerCreate': {
    Body?: NonNullable<
      paths['/api/MaaThriftControllerCreate']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaThriftControllerCreate']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaToolkitFindDevice': {
    Body?: NonNullable<
      paths['/api/MaaToolkitFindDevice']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaToolkitFindDevice']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaToolkitFindDeviceWithAdb': {
    Body?: NonNullable<
      paths['/api/MaaToolkitFindDeviceWithAdb']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaToolkitFindDeviceWithAdb']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaToolkitFindWindow': {
    Body?: NonNullable<
      paths['/api/MaaToolkitFindWindow']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaToolkitFindWindow']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaToolkitGetCursorWindow': {
    Body?: NonNullable<
      paths['/api/MaaToolkitGetCursorWindow']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaToolkitGetCursorWindow']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaToolkitGetDesktopWindow': {
    Body?: NonNullable<
      paths['/api/MaaToolkitGetDesktopWindow']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaToolkitGetDesktopWindow']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaToolkitGetDeviceAdbConfig': {
    Body?: NonNullable<
      paths['/api/MaaToolkitGetDeviceAdbConfig']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaToolkitGetDeviceAdbConfig']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaToolkitGetDeviceAdbControllerType': {
    Body?: NonNullable<
      paths['/api/MaaToolkitGetDeviceAdbControllerType']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaToolkitGetDeviceAdbControllerType']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaToolkitGetDeviceAdbPath': {
    Body?: NonNullable<
      paths['/api/MaaToolkitGetDeviceAdbPath']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaToolkitGetDeviceAdbPath']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaToolkitGetDeviceAdbSerial': {
    Body?: NonNullable<
      paths['/api/MaaToolkitGetDeviceAdbSerial']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaToolkitGetDeviceAdbSerial']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaToolkitGetDeviceCount': {
    Body?: NonNullable<
      paths['/api/MaaToolkitGetDeviceCount']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaToolkitGetDeviceCount']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaToolkitGetDeviceName': {
    Body?: NonNullable<
      paths['/api/MaaToolkitGetDeviceName']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaToolkitGetDeviceName']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaToolkitGetForegroundWindow': {
    Body?: NonNullable<
      paths['/api/MaaToolkitGetForegroundWindow']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaToolkitGetForegroundWindow']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaToolkitGetWindow': {
    Body?: NonNullable<
      paths['/api/MaaToolkitGetWindow']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaToolkitGetWindow']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaToolkitInit': {
    Body?: NonNullable<
      paths['/api/MaaToolkitInit']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaToolkitInit']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaToolkitIsFindDeviceCompleted': {
    Body?: NonNullable<
      paths['/api/MaaToolkitIsFindDeviceCompleted']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaToolkitIsFindDeviceCompleted']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaToolkitPostFindDevice': {
    Body?: NonNullable<
      paths['/api/MaaToolkitPostFindDevice']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaToolkitPostFindDevice']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaToolkitPostFindDeviceWithAdb': {
    Body?: NonNullable<
      paths['/api/MaaToolkitPostFindDeviceWithAdb']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaToolkitPostFindDeviceWithAdb']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaToolkitRegisterCustomActionExecutor': {
    Body?: NonNullable<
      paths['/api/MaaToolkitRegisterCustomActionExecutor']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaToolkitRegisterCustomActionExecutor']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaToolkitRegisterCustomRecognizerExecutor': {
    Body?: NonNullable<
      paths['/api/MaaToolkitRegisterCustomRecognizerExecutor']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaToolkitRegisterCustomRecognizerExecutor']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaToolkitSearchWindow': {
    Body?: NonNullable<
      paths['/api/MaaToolkitSearchWindow']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaToolkitSearchWindow']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaToolkitUninit': {
    Body?: NonNullable<
      paths['/api/MaaToolkitUninit']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaToolkitUninit']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaToolkitUnregisterCustomActionExecutor': {
    Body?: NonNullable<
      paths['/api/MaaToolkitUnregisterCustomActionExecutor']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaToolkitUnregisterCustomActionExecutor']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaToolkitUnregisterCustomRecognizerExecutor': {
    Body?: NonNullable<
      paths['/api/MaaToolkitUnregisterCustomRecognizerExecutor']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaToolkitUnregisterCustomRecognizerExecutor']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaToolkitWaitForFindDeviceToComplete': {
    Body?: NonNullable<
      paths['/api/MaaToolkitWaitForFindDeviceToComplete']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaToolkitWaitForFindDeviceToComplete']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaVersion': {
    Body?: NonNullable<
      paths['/api/MaaVersion']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaVersion']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaWaitTask': {
    Body?: NonNullable<
      paths['/api/MaaWaitTask']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaWaitTask']['post']['responses']['200']['content']['application/json']
  }
  '/api/MaaWin32ControllerCreate': {
    Body?: NonNullable<
      paths['/api/MaaWin32ControllerCreate']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/api/MaaWin32ControllerCreate']['post']['responses']['200']['content']['application/json']
  }
  '/callback/MaaAPICallback/add': {
    Body?: NonNullable<
      paths['/callback/MaaAPICallback/add']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/callback/MaaAPICallback/add']['post']['responses']['200']['content']['application/json']
  }
  '/callback/MaaAPICallback/del': {
    Body?: NonNullable<
      paths['/callback/MaaAPICallback/del']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/callback/MaaAPICallback/del']['post']['responses']['200']['content']['application/json']
  }
  '/callback/MaaAPICallback/dump': {
    Body?: NonNullable<
      paths['/callback/MaaAPICallback/dump']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/callback/MaaAPICallback/dump']['post']['responses']['200']['content']['application/json']
  }
  '/callback/MaaAPICallback/pull': {
    Body?: NonNullable<
      paths['/callback/MaaAPICallback/pull']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/callback/MaaAPICallback/pull']['post']['responses']['200']['content']['application/json']
  }
  '/callback/MaaAPICallback/request': {
    Body?: NonNullable<
      paths['/callback/MaaAPICallback/request']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/callback/MaaAPICallback/request']['post']['responses']['200']['content']['application/json']
  }
  '/callback/MaaAPICallback/response': {
    Body?: NonNullable<
      paths['/callback/MaaAPICallback/response']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/callback/MaaAPICallback/response']['post']['responses']['200']['content']['application/json']
  }
  '/opaque/MaaControllerAPI': {
    Body?: NonNullable<
      paths['/opaque/MaaControllerAPI']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/opaque/MaaControllerAPI']['post']['responses']['200']['content']['application/json']
  }
  '/opaque/MaaImageBuffer': {
    Body?: NonNullable<
      paths['/opaque/MaaImageBuffer']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/opaque/MaaImageBuffer']['post']['responses']['200']['content']['application/json']
  }
  '/opaque/MaaInstanceAPI': {
    Body?: NonNullable<
      paths['/opaque/MaaInstanceAPI']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/opaque/MaaInstanceAPI']['post']['responses']['200']['content']['application/json']
  }
  '/opaque/MaaResourceAPI': {
    Body?: NonNullable<
      paths['/opaque/MaaResourceAPI']['post']['requestBody']
    >['content']['application/json']
    Response: paths['/opaque/MaaResourceAPI']['post']['responses']['200']['content']['application/json']
  }
}
