/**
 * This file was auto-generated by @liangskyli/openapi-gen-ts.
 * Do not make direct changes to the file.
 */
import type { paths } from './ts-schema'

export interface IApi {
  '/api/MaaAdbControllerCreateV2': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaAdbControllerCreateV2']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaAdbControllerCreateV2']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaBindController': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaBindController']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaBindController']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaBindResource': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaBindResource']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaBindResource']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaClearCustomAction': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaClearCustomAction']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaClearCustomAction']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaClearCustomRecognizer': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaClearCustomRecognizer']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaClearCustomRecognizer']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaClearImage': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaClearImage']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaClearImage']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaControllerConnected': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaControllerConnected']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaControllerConnected']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaControllerDestroy': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaControllerDestroy']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaControllerDestroy']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaControllerGetImage': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaControllerGetImage']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaControllerGetImage']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaControllerGetUUID': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaControllerGetUUID']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaControllerGetUUID']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaControllerPostClick': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaControllerPostClick']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaControllerPostClick']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaControllerPostConnection': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaControllerPostConnection']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaControllerPostConnection']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaControllerPostInputText': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaControllerPostInputText']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaControllerPostInputText']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaControllerPostPressKey': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaControllerPostPressKey']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaControllerPostPressKey']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaControllerPostScreencap': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaControllerPostScreencap']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaControllerPostScreencap']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaControllerPostSwipe': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaControllerPostSwipe']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaControllerPostSwipe']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaControllerPostTouchDown': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaControllerPostTouchDown']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaControllerPostTouchDown']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaControllerPostTouchMove': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaControllerPostTouchMove']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaControllerPostTouchMove']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaControllerPostTouchUp': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaControllerPostTouchUp']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaControllerPostTouchUp']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaControllerSetOptionBoolean': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaControllerSetOptionBoolean']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaControllerSetOptionBoolean']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaControllerSetOptionInteger': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaControllerSetOptionInteger']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaControllerSetOptionInteger']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaControllerSetOptionString': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaControllerSetOptionString']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaControllerSetOptionString']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaControllerStatus': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaControllerStatus']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaControllerStatus']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaControllerWait': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaControllerWait']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaControllerWait']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaCreate': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaCreate']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaCreate']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaCreateImageBuffer': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaCreateImageBuffer']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaCreateImageBuffer']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaDbgControllerCreate': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaDbgControllerCreate']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaDbgControllerCreate']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaDestroy': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaDestroy']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaDestroy']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaDestroyImageBuffer': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaDestroyImageBuffer']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaDestroyImageBuffer']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaGetController': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaGetController']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaGetController']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaGetImageEncoded': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaGetImageEncoded']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaGetImageEncoded']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaGetImageHeight': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaGetImageHeight']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaGetImageHeight']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaGetImageType': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaGetImageType']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaGetImageType']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaGetImageWidth': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaGetImageWidth']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaGetImageWidth']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaGetResource': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaGetResource']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaGetResource']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaInited': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaInited']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaInited']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaIsImageEmpty': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaIsImageEmpty']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaIsImageEmpty']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaPostStop': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaPostStop']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaPostStop']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaPostTask': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaPostTask']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaPostTask']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaRegisterCustomAction': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaRegisterCustomAction']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaRegisterCustomAction']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaRegisterCustomRecognizer': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaRegisterCustomRecognizer']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaRegisterCustomRecognizer']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaResourceClear': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaResourceClear']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaResourceClear']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaResourceCreate': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaResourceCreate']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaResourceCreate']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaResourceDestroy': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaResourceDestroy']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaResourceDestroy']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaResourceGetHash': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaResourceGetHash']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaResourceGetHash']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaResourceGetTaskList': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaResourceGetTaskList']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaResourceGetTaskList']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaResourceLoaded': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaResourceLoaded']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaResourceLoaded']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaResourcePostPath': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaResourcePostPath']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaResourcePostPath']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaResourceStatus': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaResourceStatus']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaResourceStatus']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaResourceWait': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaResourceWait']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaResourceWait']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaRunning': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaRunning']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaRunning']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaSetGlobalOptionBoolean': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaSetGlobalOptionBoolean']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaSetGlobalOptionBoolean']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaSetGlobalOptionInteger': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaSetGlobalOptionInteger']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaSetGlobalOptionInteger']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaSetGlobalOptionString': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaSetGlobalOptionString']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaSetGlobalOptionString']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaSetImageEncoded': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaSetImageEncoded']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaSetImageEncoded']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaSetTaskParam': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaSetTaskParam']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaSetTaskParam']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaSyncContextClick': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaSyncContextClick']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaSyncContextClick']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaSyncContextGetTaskResult': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaSyncContextGetTaskResult']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaSyncContextGetTaskResult']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaSyncContextInputText': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaSyncContextInputText']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaSyncContextInputText']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaSyncContextPressKey': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaSyncContextPressKey']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaSyncContextPressKey']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaSyncContextRunAction': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaSyncContextRunAction']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaSyncContextRunAction']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaSyncContextRunRecognizer': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaSyncContextRunRecognizer']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaSyncContextRunRecognizer']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaSyncContextRunTask': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaSyncContextRunTask']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaSyncContextRunTask']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaSyncContextScreencap': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaSyncContextScreencap']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaSyncContextScreencap']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaSyncContextSwipe': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaSyncContextSwipe']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaSyncContextSwipe']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaSyncContextTouchDown': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaSyncContextTouchDown']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaSyncContextTouchDown']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaSyncContextTouchMove': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaSyncContextTouchMove']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaSyncContextTouchMove']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaSyncContextTouchUp': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaSyncContextTouchUp']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaSyncContextTouchUp']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaTaskStatus': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaTaskStatus']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaTaskStatus']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaThriftControllerCreate': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaThriftControllerCreate']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaThriftControllerCreate']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaToolkitFindWindow': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaToolkitFindWindow']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaToolkitFindWindow']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaToolkitGetCursorWindow': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaToolkitGetCursorWindow']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaToolkitGetCursorWindow']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaToolkitGetDesktopWindow': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaToolkitGetDesktopWindow']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaToolkitGetDesktopWindow']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaToolkitGetDeviceAdbConfig': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaToolkitGetDeviceAdbConfig']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaToolkitGetDeviceAdbConfig']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaToolkitGetDeviceAdbControllerType': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaToolkitGetDeviceAdbControllerType']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaToolkitGetDeviceAdbControllerType']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaToolkitGetDeviceAdbPath': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaToolkitGetDeviceAdbPath']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaToolkitGetDeviceAdbPath']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaToolkitGetDeviceAdbSerial': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaToolkitGetDeviceAdbSerial']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaToolkitGetDeviceAdbSerial']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaToolkitGetDeviceCount': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaToolkitGetDeviceCount']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaToolkitGetDeviceCount']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaToolkitGetDeviceName': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaToolkitGetDeviceName']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaToolkitGetDeviceName']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaToolkitGetForegroundWindow': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaToolkitGetForegroundWindow']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaToolkitGetForegroundWindow']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaToolkitGetWindow': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaToolkitGetWindow']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaToolkitGetWindow']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaToolkitInitOptionConfig': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaToolkitInitOptionConfig']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaToolkitInitOptionConfig']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaToolkitIsFindDeviceCompleted': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaToolkitIsFindDeviceCompleted']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaToolkitIsFindDeviceCompleted']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaToolkitPostFindDevice': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaToolkitPostFindDevice']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaToolkitPostFindDevice']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaToolkitPostFindDeviceWithAdb': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaToolkitPostFindDeviceWithAdb']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaToolkitPostFindDeviceWithAdb']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaToolkitRegisterCustomActionExecutor': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaToolkitRegisterCustomActionExecutor']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaToolkitRegisterCustomActionExecutor']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaToolkitRegisterCustomRecognizerExecutor': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaToolkitRegisterCustomRecognizerExecutor']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaToolkitRegisterCustomRecognizerExecutor']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaToolkitSearchWindow': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaToolkitSearchWindow']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaToolkitSearchWindow']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaToolkitUnregisterCustomActionExecutor': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaToolkitUnregisterCustomActionExecutor']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaToolkitUnregisterCustomActionExecutor']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaToolkitUnregisterCustomRecognizerExecutor': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaToolkitUnregisterCustomRecognizerExecutor']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaToolkitUnregisterCustomRecognizerExecutor']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaToolkitWaitForFindDeviceToComplete': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaToolkitWaitForFindDeviceToComplete']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaToolkitWaitForFindDeviceToComplete']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaUnregisterCustomAction': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaUnregisterCustomAction']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaUnregisterCustomAction']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaUnregisterCustomRecognizer': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaUnregisterCustomRecognizer']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaUnregisterCustomRecognizer']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaVersion': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaVersion']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaVersion']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaWaitTask': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaWaitTask']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaWaitTask']['post']['responses']['200']['content']['application/json']
    }
  }
  '/api/MaaWin32ControllerCreate': {
    post: {
      Body?: NonNullable<
        paths['/api/MaaWin32ControllerCreate']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/api/MaaWin32ControllerCreate']['post']['responses']['200']['content']['application/json']
    }
  }
  '/callback/CustomActionRun/dump': {
    post: {
      Body?: NonNullable<
        paths['/callback/CustomActionRun/dump']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/callback/CustomActionRun/dump']['post']['responses']['200']['content']['application/json']
    }
  }
  '/callback/CustomActionRun/free': {
    post: {
      Body?: NonNullable<
        paths['/callback/CustomActionRun/free']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/callback/CustomActionRun/free']['post']['responses']['200']['content']['application/json']
    }
  }
  '/callback/CustomActionRun/new': {
    post: {
      Body?: NonNullable<
        paths['/callback/CustomActionRun/new']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/callback/CustomActionRun/new']['post']['responses']['200']['content']['application/json']
    }
  }
  '/callback/CustomActionRun/query': {
    post: {
      Body?: NonNullable<
        paths['/callback/CustomActionRun/query']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/callback/CustomActionRun/query']['post']['responses']['200']['content']['application/json']
    }
  }
  '/callback/CustomActionRun/req': {
    post: {
      Body?: NonNullable<
        paths['/callback/CustomActionRun/req']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/callback/CustomActionRun/req']['post']['responses']['200']['content']['application/json']
    }
  }
  '/callback/CustomActionRun/res': {
    post: {
      Body?: NonNullable<
        paths['/callback/CustomActionRun/res']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/callback/CustomActionRun/res']['post']['responses']['200']['content']['application/json']
    }
  }
  '/callback/CustomActionStop/dump': {
    post: {
      Body?: NonNullable<
        paths['/callback/CustomActionStop/dump']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/callback/CustomActionStop/dump']['post']['responses']['200']['content']['application/json']
    }
  }
  '/callback/CustomActionStop/free': {
    post: {
      Body?: NonNullable<
        paths['/callback/CustomActionStop/free']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/callback/CustomActionStop/free']['post']['responses']['200']['content']['application/json']
    }
  }
  '/callback/CustomActionStop/new': {
    post: {
      Body?: NonNullable<
        paths['/callback/CustomActionStop/new']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/callback/CustomActionStop/new']['post']['responses']['200']['content']['application/json']
    }
  }
  '/callback/CustomActionStop/query': {
    post: {
      Body?: NonNullable<
        paths['/callback/CustomActionStop/query']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/callback/CustomActionStop/query']['post']['responses']['200']['content']['application/json']
    }
  }
  '/callback/CustomActionStop/req': {
    post: {
      Body?: NonNullable<
        paths['/callback/CustomActionStop/req']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/callback/CustomActionStop/req']['post']['responses']['200']['content']['application/json']
    }
  }
  '/callback/CustomActionStop/res': {
    post: {
      Body?: NonNullable<
        paths['/callback/CustomActionStop/res']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/callback/CustomActionStop/res']['post']['responses']['200']['content']['application/json']
    }
  }
  '/callback/CustomRecognizerAnalyze/dump': {
    post: {
      Body?: NonNullable<
        paths['/callback/CustomRecognizerAnalyze/dump']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/callback/CustomRecognizerAnalyze/dump']['post']['responses']['200']['content']['application/json']
    }
  }
  '/callback/CustomRecognizerAnalyze/free': {
    post: {
      Body?: NonNullable<
        paths['/callback/CustomRecognizerAnalyze/free']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/callback/CustomRecognizerAnalyze/free']['post']['responses']['200']['content']['application/json']
    }
  }
  '/callback/CustomRecognizerAnalyze/new': {
    post: {
      Body?: NonNullable<
        paths['/callback/CustomRecognizerAnalyze/new']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/callback/CustomRecognizerAnalyze/new']['post']['responses']['200']['content']['application/json']
    }
  }
  '/callback/CustomRecognizerAnalyze/query': {
    post: {
      Body?: NonNullable<
        paths['/callback/CustomRecognizerAnalyze/query']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/callback/CustomRecognizerAnalyze/query']['post']['responses']['200']['content']['application/json']
    }
  }
  '/callback/CustomRecognizerAnalyze/req': {
    post: {
      Body?: NonNullable<
        paths['/callback/CustomRecognizerAnalyze/req']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/callback/CustomRecognizerAnalyze/req']['post']['responses']['200']['content']['application/json']
    }
  }
  '/callback/CustomRecognizerAnalyze/res': {
    post: {
      Body?: NonNullable<
        paths['/callback/CustomRecognizerAnalyze/res']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/callback/CustomRecognizerAnalyze/res']['post']['responses']['200']['content']['application/json']
    }
  }
  '/callback/MaaAPICallback/dump': {
    post: {
      Body?: NonNullable<
        paths['/callback/MaaAPICallback/dump']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/callback/MaaAPICallback/dump']['post']['responses']['200']['content']['application/json']
    }
  }
  '/callback/MaaAPICallback/free': {
    post: {
      Body?: NonNullable<
        paths['/callback/MaaAPICallback/free']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/callback/MaaAPICallback/free']['post']['responses']['200']['content']['application/json']
    }
  }
  '/callback/MaaAPICallback/new': {
    post: {
      Body?: NonNullable<
        paths['/callback/MaaAPICallback/new']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/callback/MaaAPICallback/new']['post']['responses']['200']['content']['application/json']
    }
  }
  '/callback/MaaAPICallback/query': {
    post: {
      Body?: NonNullable<
        paths['/callback/MaaAPICallback/query']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/callback/MaaAPICallback/query']['post']['responses']['200']['content']['application/json']
    }
  }
  '/callback/MaaAPICallback/req': {
    post: {
      Body?: NonNullable<
        paths['/callback/MaaAPICallback/req']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/callback/MaaAPICallback/req']['post']['responses']['200']['content']['application/json']
    }
  }
  '/callback/MaaAPICallback/res': {
    post: {
      Body?: NonNullable<
        paths['/callback/MaaAPICallback/res']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/callback/MaaAPICallback/res']['post']['responses']['200']['content']['application/json']
    }
  }
  '/handle/MaaControllerAPI/dump': {
    post: {
      Body?: NonNullable<
        paths['/handle/MaaControllerAPI/dump']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/handle/MaaControllerAPI/dump']['post']['responses']['200']['content']['application/json']
    }
  }
  '/handle/MaaImageBuffer/dump': {
    post: {
      Body?: NonNullable<
        paths['/handle/MaaImageBuffer/dump']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/handle/MaaImageBuffer/dump']['post']['responses']['200']['content']['application/json']
    }
  }
  '/handle/MaaInstanceAPI/dump': {
    post: {
      Body?: NonNullable<
        paths['/handle/MaaInstanceAPI/dump']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/handle/MaaInstanceAPI/dump']['post']['responses']['200']['content']['application/json']
    }
  }
  '/handle/MaaResourceAPI/dump': {
    post: {
      Body?: NonNullable<
        paths['/handle/MaaResourceAPI/dump']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/handle/MaaResourceAPI/dump']['post']['responses']['200']['content']['application/json']
    }
  }
  '/handle/MaaSyncContextAPI/dump': {
    post: {
      Body?: NonNullable<
        paths['/handle/MaaSyncContextAPI/dump']['post']['requestBody']
      >['content']['application/json']
      Response: paths['/handle/MaaSyncContextAPI/dump']['post']['responses']['200']['content']['application/json']
    }
  }
  '/help': {
    post: {
      Body?: NonNullable<paths['/help']['post']['requestBody']>['content']['application/json']
      Response: paths['/help']['post']['responses']['200']['content']['application/json']
    }
  }
}
