/**
 * This file was auto-generated by @liangskyli/openapi-gen-ts.
 * Do not make direct changes to the file.
 */
import type { IApi } from './interface-api'
import type { AxiosRequestConfig } from './request'
import request from './request'

type IConfig<T extends Record<any, any> | unknown, U extends Record<any, any>> = T & U
type Equal<T, U> =
  (<P>(x: P) => P extends T ? 1 : 2) extends <P>(x: P) => P extends U ? 1 : 2 ? true : false

export const requestApi = {
  '/api/MaaAdbControllerCreate': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaAdbControllerCreate']['Body'] }
    >
  ): Promise<IApi['/api/MaaAdbControllerCreate']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaAdbControllerCreate'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaAdbControllerCreateV2': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaAdbControllerCreateV2']['Body'] }
    >
  ): Promise<IApi['/api/MaaAdbControllerCreateV2']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaAdbControllerCreateV2'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaBindController': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaBindController']['Body'] }
    >
  ): Promise<IApi['/api/MaaBindController']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaBindController'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaBindResource': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaBindResource']['Body'] }
    >
  ): Promise<IApi['/api/MaaBindResource']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaBindResource'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaClearCustomAction': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaClearCustomAction']['Body'] }
    >
  ): Promise<IApi['/api/MaaClearCustomAction']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaClearCustomAction'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaClearCustomRecognizer': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaClearCustomRecognizer']['Body'] }
    >
  ): Promise<IApi['/api/MaaClearCustomRecognizer']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaClearCustomRecognizer'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaClearImage': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaClearImage']['Body'] }
    >
  ): Promise<IApi['/api/MaaClearImage']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaClearImage'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaControllerConnected': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaControllerConnected']['Body'] }
    >
  ): Promise<IApi['/api/MaaControllerConnected']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaControllerConnected'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaControllerDestroy': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaControllerDestroy']['Body'] }
    >
  ): Promise<IApi['/api/MaaControllerDestroy']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaControllerDestroy'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaControllerGetImage': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaControllerGetImage']['Body'] }
    >
  ): Promise<IApi['/api/MaaControllerGetImage']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaControllerGetImage'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaControllerGetUUID': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaControllerGetUUID']['Body'] }
    >
  ): Promise<IApi['/api/MaaControllerGetUUID']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaControllerGetUUID'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaControllerPostClick': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaControllerPostClick']['Body'] }
    >
  ): Promise<IApi['/api/MaaControllerPostClick']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaControllerPostClick'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaControllerPostConnection': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaControllerPostConnection']['Body'] }
    >
  ): Promise<IApi['/api/MaaControllerPostConnection']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaControllerPostConnection'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaControllerPostInputText': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaControllerPostInputText']['Body'] }
    >
  ): Promise<IApi['/api/MaaControllerPostInputText']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaControllerPostInputText'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaControllerPostPressKey': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaControllerPostPressKey']['Body'] }
    >
  ): Promise<IApi['/api/MaaControllerPostPressKey']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaControllerPostPressKey'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaControllerPostScreencap': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaControllerPostScreencap']['Body'] }
    >
  ): Promise<IApi['/api/MaaControllerPostScreencap']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaControllerPostScreencap'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaControllerPostSwipe': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaControllerPostSwipe']['Body'] }
    >
  ): Promise<IApi['/api/MaaControllerPostSwipe']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaControllerPostSwipe'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaControllerPostTouchDown': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaControllerPostTouchDown']['Body'] }
    >
  ): Promise<IApi['/api/MaaControllerPostTouchDown']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaControllerPostTouchDown'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaControllerPostTouchMove': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaControllerPostTouchMove']['Body'] }
    >
  ): Promise<IApi['/api/MaaControllerPostTouchMove']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaControllerPostTouchMove'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaControllerPostTouchUp': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaControllerPostTouchUp']['Body'] }
    >
  ): Promise<IApi['/api/MaaControllerPostTouchUp']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaControllerPostTouchUp'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaControllerSetOptionBoolean': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaControllerSetOptionBoolean']['Body'] }
    >
  ): Promise<IApi['/api/MaaControllerSetOptionBoolean']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaControllerSetOptionBoolean'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaControllerSetOptionInteger': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaControllerSetOptionInteger']['Body'] }
    >
  ): Promise<IApi['/api/MaaControllerSetOptionInteger']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaControllerSetOptionInteger'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaControllerSetOptionString': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaControllerSetOptionString']['Body'] }
    >
  ): Promise<IApi['/api/MaaControllerSetOptionString']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaControllerSetOptionString'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaControllerStatus': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaControllerStatus']['Body'] }
    >
  ): Promise<IApi['/api/MaaControllerStatus']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaControllerStatus'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaControllerWait': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaControllerWait']['Body'] }
    >
  ): Promise<IApi['/api/MaaControllerWait']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaControllerWait'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaCreate': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaCreate']['Body'] }
    >
  ): Promise<IApi['/api/MaaCreate']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaCreate'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaCreateImageBuffer': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaCreateImageBuffer']['Body'] }
    >
  ): Promise<IApi['/api/MaaCreateImageBuffer']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaCreateImageBuffer'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaDbgControllerCreate': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaDbgControllerCreate']['Body'] }
    >
  ): Promise<IApi['/api/MaaDbgControllerCreate']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaDbgControllerCreate'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaDestroy': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaDestroy']['Body'] }
    >
  ): Promise<IApi['/api/MaaDestroy']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaDestroy'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaDestroyImageBuffer': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaDestroyImageBuffer']['Body'] }
    >
  ): Promise<IApi['/api/MaaDestroyImageBuffer']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaDestroyImageBuffer'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaGetController': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaGetController']['Body'] }
    >
  ): Promise<IApi['/api/MaaGetController']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaGetController'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaGetImageEncoded': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaGetImageEncoded']['Body'] }
    >
  ): Promise<IApi['/api/MaaGetImageEncoded']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaGetImageEncoded'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaGetImageHeight': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaGetImageHeight']['Body'] }
    >
  ): Promise<IApi['/api/MaaGetImageHeight']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaGetImageHeight'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaGetImageType': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaGetImageType']['Body'] }
    >
  ): Promise<IApi['/api/MaaGetImageType']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaGetImageType'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaGetImageWidth': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaGetImageWidth']['Body'] }
    >
  ): Promise<IApi['/api/MaaGetImageWidth']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaGetImageWidth'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaGetResource': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaGetResource']['Body'] }
    >
  ): Promise<IApi['/api/MaaGetResource']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaGetResource'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaInited': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaInited']['Body'] }
    >
  ): Promise<IApi['/api/MaaInited']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaInited'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaIsImageEmpty': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaIsImageEmpty']['Body'] }
    >
  ): Promise<IApi['/api/MaaIsImageEmpty']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaIsImageEmpty'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaPostStop': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaPostStop']['Body'] }
    >
  ): Promise<IApi['/api/MaaPostStop']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaPostStop'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaPostTask': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaPostTask']['Body'] }
    >
  ): Promise<IApi['/api/MaaPostTask']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaPostTask'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaResourceCreate': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaResourceCreate']['Body'] }
    >
  ): Promise<IApi['/api/MaaResourceCreate']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaResourceCreate'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaResourceDestroy': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaResourceDestroy']['Body'] }
    >
  ): Promise<IApi['/api/MaaResourceDestroy']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaResourceDestroy'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaResourceGetHash': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaResourceGetHash']['Body'] }
    >
  ): Promise<IApi['/api/MaaResourceGetHash']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaResourceGetHash'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaResourceGetTaskList': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaResourceGetTaskList']['Body'] }
    >
  ): Promise<IApi['/api/MaaResourceGetTaskList']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaResourceGetTaskList'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaResourceLoaded': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaResourceLoaded']['Body'] }
    >
  ): Promise<IApi['/api/MaaResourceLoaded']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaResourceLoaded'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaResourcePostPath': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaResourcePostPath']['Body'] }
    >
  ): Promise<IApi['/api/MaaResourcePostPath']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaResourcePostPath'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaResourceStatus': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaResourceStatus']['Body'] }
    >
  ): Promise<IApi['/api/MaaResourceStatus']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaResourceStatus'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaResourceWait': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaResourceWait']['Body'] }
    >
  ): Promise<IApi['/api/MaaResourceWait']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaResourceWait'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaSetGlobalOptionBoolean': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaSetGlobalOptionBoolean']['Body'] }
    >
  ): Promise<IApi['/api/MaaSetGlobalOptionBoolean']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaSetGlobalOptionBoolean'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaSetGlobalOptionInteger': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaSetGlobalOptionInteger']['Body'] }
    >
  ): Promise<IApi['/api/MaaSetGlobalOptionInteger']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaSetGlobalOptionInteger'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaSetGlobalOptionString': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaSetGlobalOptionString']['Body'] }
    >
  ): Promise<IApi['/api/MaaSetGlobalOptionString']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaSetGlobalOptionString'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaSetImageEncoded': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaSetImageEncoded']['Body'] }
    >
  ): Promise<IApi['/api/MaaSetImageEncoded']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaSetImageEncoded'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaSetTaskParam': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaSetTaskParam']['Body'] }
    >
  ): Promise<IApi['/api/MaaSetTaskParam']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaSetTaskParam'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaStop': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaStop']['Body'] }
    >
  ): Promise<IApi['/api/MaaStop']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaStop'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaTaskAllFinished': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaTaskAllFinished']['Body'] }
    >
  ): Promise<IApi['/api/MaaTaskAllFinished']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaTaskAllFinished'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaTaskStatus': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaTaskStatus']['Body'] }
    >
  ): Promise<IApi['/api/MaaTaskStatus']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaTaskStatus'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaThriftControllerCreate': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaThriftControllerCreate']['Body'] }
    >
  ): Promise<IApi['/api/MaaThriftControllerCreate']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaThriftControllerCreate'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaToolkitFindDevice': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaToolkitFindDevice']['Body'] }
    >
  ): Promise<IApi['/api/MaaToolkitFindDevice']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaToolkitFindDevice'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaToolkitFindDeviceWithAdb': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaToolkitFindDeviceWithAdb']['Body'] }
    >
  ): Promise<IApi['/api/MaaToolkitFindDeviceWithAdb']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaToolkitFindDeviceWithAdb'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaToolkitFindWindow': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaToolkitFindWindow']['Body'] }
    >
  ): Promise<IApi['/api/MaaToolkitFindWindow']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaToolkitFindWindow'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaToolkitGetCursorWindow': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaToolkitGetCursorWindow']['Body'] }
    >
  ): Promise<IApi['/api/MaaToolkitGetCursorWindow']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaToolkitGetCursorWindow'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaToolkitGetDesktopWindow': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaToolkitGetDesktopWindow']['Body'] }
    >
  ): Promise<IApi['/api/MaaToolkitGetDesktopWindow']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaToolkitGetDesktopWindow'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaToolkitGetDeviceAdbConfig': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaToolkitGetDeviceAdbConfig']['Body'] }
    >
  ): Promise<IApi['/api/MaaToolkitGetDeviceAdbConfig']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaToolkitGetDeviceAdbConfig'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaToolkitGetDeviceAdbControllerType': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaToolkitGetDeviceAdbControllerType']['Body'] }
    >
  ): Promise<IApi['/api/MaaToolkitGetDeviceAdbControllerType']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaToolkitGetDeviceAdbControllerType'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaToolkitGetDeviceAdbPath': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaToolkitGetDeviceAdbPath']['Body'] }
    >
  ): Promise<IApi['/api/MaaToolkitGetDeviceAdbPath']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaToolkitGetDeviceAdbPath'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaToolkitGetDeviceAdbSerial': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaToolkitGetDeviceAdbSerial']['Body'] }
    >
  ): Promise<IApi['/api/MaaToolkitGetDeviceAdbSerial']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaToolkitGetDeviceAdbSerial'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaToolkitGetDeviceCount': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaToolkitGetDeviceCount']['Body'] }
    >
  ): Promise<IApi['/api/MaaToolkitGetDeviceCount']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaToolkitGetDeviceCount'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaToolkitGetDeviceName': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaToolkitGetDeviceName']['Body'] }
    >
  ): Promise<IApi['/api/MaaToolkitGetDeviceName']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaToolkitGetDeviceName'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaToolkitGetForegroundWindow': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaToolkitGetForegroundWindow']['Body'] }
    >
  ): Promise<IApi['/api/MaaToolkitGetForegroundWindow']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaToolkitGetForegroundWindow'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaToolkitGetWindow': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaToolkitGetWindow']['Body'] }
    >
  ): Promise<IApi['/api/MaaToolkitGetWindow']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaToolkitGetWindow'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaToolkitInit': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaToolkitInit']['Body'] }
    >
  ): Promise<IApi['/api/MaaToolkitInit']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaToolkitInit'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaToolkitIsFindDeviceCompleted': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaToolkitIsFindDeviceCompleted']['Body'] }
    >
  ): Promise<IApi['/api/MaaToolkitIsFindDeviceCompleted']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaToolkitIsFindDeviceCompleted'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaToolkitPostFindDevice': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaToolkitPostFindDevice']['Body'] }
    >
  ): Promise<IApi['/api/MaaToolkitPostFindDevice']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaToolkitPostFindDevice'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaToolkitPostFindDeviceWithAdb': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaToolkitPostFindDeviceWithAdb']['Body'] }
    >
  ): Promise<IApi['/api/MaaToolkitPostFindDeviceWithAdb']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaToolkitPostFindDeviceWithAdb'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaToolkitRegisterCustomActionExecutor': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaToolkitRegisterCustomActionExecutor']['Body'] }
    >
  ): Promise<IApi['/api/MaaToolkitRegisterCustomActionExecutor']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaToolkitRegisterCustomActionExecutor'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaToolkitRegisterCustomRecognizerExecutor': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaToolkitRegisterCustomRecognizerExecutor']['Body'] }
    >
  ): Promise<IApi['/api/MaaToolkitRegisterCustomRecognizerExecutor']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaToolkitRegisterCustomRecognizerExecutor'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaToolkitSearchWindow': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaToolkitSearchWindow']['Body'] }
    >
  ): Promise<IApi['/api/MaaToolkitSearchWindow']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaToolkitSearchWindow'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaToolkitUninit': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaToolkitUninit']['Body'] }
    >
  ): Promise<IApi['/api/MaaToolkitUninit']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaToolkitUninit'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaToolkitUnregisterCustomActionExecutor': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaToolkitUnregisterCustomActionExecutor']['Body'] }
    >
  ): Promise<IApi['/api/MaaToolkitUnregisterCustomActionExecutor']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaToolkitUnregisterCustomActionExecutor'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaToolkitUnregisterCustomRecognizerExecutor': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaToolkitUnregisterCustomRecognizerExecutor']['Body'] }
    >
  ): Promise<IApi['/api/MaaToolkitUnregisterCustomRecognizerExecutor']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaToolkitUnregisterCustomRecognizerExecutor'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaToolkitWaitForFindDeviceToComplete': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaToolkitWaitForFindDeviceToComplete']['Body'] }
    >
  ): Promise<IApi['/api/MaaToolkitWaitForFindDeviceToComplete']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaToolkitWaitForFindDeviceToComplete'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaVersion': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaVersion']['Body'] }
    >
  ): Promise<IApi['/api/MaaVersion']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaVersion'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaWaitTask': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaWaitTask']['Body'] }
    >
  ): Promise<IApi['/api/MaaWaitTask']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaWaitTask'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/api/MaaWin32ControllerCreate': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/api/MaaWin32ControllerCreate']['Body'] }
    >
  ): Promise<IApi['/api/MaaWin32ControllerCreate']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/api/MaaWin32ControllerCreate'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/callback/MaaAPICallback/add': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/callback/MaaAPICallback/add']['Body'] }
    >
  ): Promise<IApi['/callback/MaaAPICallback/add']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/callback/MaaAPICallback/add'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/callback/MaaAPICallback/del': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/callback/MaaAPICallback/del']['Body'] }
    >
  ): Promise<IApi['/callback/MaaAPICallback/del']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/callback/MaaAPICallback/del'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/callback/MaaAPICallback/dump': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/callback/MaaAPICallback/dump']['Body'] }
    >
  ): Promise<IApi['/callback/MaaAPICallback/dump']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/callback/MaaAPICallback/dump'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/callback/MaaAPICallback/pull': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/callback/MaaAPICallback/pull']['Body'] }
    >
  ): Promise<IApi['/callback/MaaAPICallback/pull']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/callback/MaaAPICallback/pull'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/callback/MaaAPICallback/request': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/callback/MaaAPICallback/request']['Body'] }
    >
  ): Promise<IApi['/callback/MaaAPICallback/request']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/callback/MaaAPICallback/request'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/callback/MaaAPICallback/response': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/callback/MaaAPICallback/response']['Body'] }
    >
  ): Promise<IApi['/callback/MaaAPICallback/response']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/callback/MaaAPICallback/response'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/opaque/MaaControllerAPI': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/opaque/MaaControllerAPI']['Body'] }
    >
  ): Promise<IApi['/opaque/MaaControllerAPI']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/opaque/MaaControllerAPI'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/opaque/MaaImageBuffer': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/opaque/MaaImageBuffer']['Body'] }
    >
  ): Promise<IApi['/opaque/MaaImageBuffer']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/opaque/MaaImageBuffer'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/opaque/MaaInstanceAPI': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/opaque/MaaInstanceAPI']['Body'] }
    >
  ): Promise<IApi['/opaque/MaaInstanceAPI']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/opaque/MaaInstanceAPI'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  },
  '/opaque/MaaResourceAPI': <T extends Record<any, any> | never = never>(
    config: IConfig<
      Omit<
        Equal<T, never> extends true ? AxiosRequestConfig : T & AxiosRequestConfig,
        'method' | 'url' | 'data'
      >,
      { data?: IApi['/opaque/MaaResourceAPI']['Body'] }
    >
  ): Promise<IApi['/opaque/MaaResourceAPI']['Response']> => {
    const { data, ...otherConfig } = config
    const finalURL = '/opaque/MaaResourceAPI'

    return request({
      method: 'post',
      url: finalURL,

      data: data,
      ...otherConfig
    })
  }
}
