/**
 * This file was auto-generated by @liangskyli/openapi-gen-ts.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/MaaAdbControllerCreateV2': {
    post: operations['_api_MaaAdbControllerCreateV2']
  }
  '/api/MaaBindController': {
    post: operations['_api_MaaBindController']
  }
  '/api/MaaBindResource': {
    post: operations['_api_MaaBindResource']
  }
  '/api/MaaClearCustomAction': {
    post: operations['_api_MaaClearCustomAction']
  }
  '/api/MaaClearCustomRecognizer': {
    post: operations['_api_MaaClearCustomRecognizer']
  }
  '/api/MaaClearImage': {
    post: operations['_api_MaaClearImage']
  }
  '/api/MaaControllerConnected': {
    post: operations['_api_MaaControllerConnected']
  }
  '/api/MaaControllerDestroy': {
    post: operations['_api_MaaControllerDestroy']
  }
  '/api/MaaControllerGetImage': {
    post: operations['_api_MaaControllerGetImage']
  }
  '/api/MaaControllerGetUUID': {
    post: operations['_api_MaaControllerGetUUID']
  }
  '/api/MaaControllerPostClick': {
    post: operations['_api_MaaControllerPostClick']
  }
  '/api/MaaControllerPostConnection': {
    post: operations['_api_MaaControllerPostConnection']
  }
  '/api/MaaControllerPostInputText': {
    post: operations['_api_MaaControllerPostInputText']
  }
  '/api/MaaControllerPostPressKey': {
    post: operations['_api_MaaControllerPostPressKey']
  }
  '/api/MaaControllerPostScreencap': {
    post: operations['_api_MaaControllerPostScreencap']
  }
  '/api/MaaControllerPostSwipe': {
    post: operations['_api_MaaControllerPostSwipe']
  }
  '/api/MaaControllerPostTouchDown': {
    post: operations['_api_MaaControllerPostTouchDown']
  }
  '/api/MaaControllerPostTouchMove': {
    post: operations['_api_MaaControllerPostTouchMove']
  }
  '/api/MaaControllerPostTouchUp': {
    post: operations['_api_MaaControllerPostTouchUp']
  }
  '/api/MaaControllerSetOptionBoolean': {
    post: operations['_api_MaaControllerSetOptionBoolean']
  }
  '/api/MaaControllerSetOptionInteger': {
    post: operations['_api_MaaControllerSetOptionInteger']
  }
  '/api/MaaControllerSetOptionString': {
    post: operations['_api_MaaControllerSetOptionString']
  }
  '/api/MaaControllerStatus': {
    post: operations['_api_MaaControllerStatus']
  }
  '/api/MaaControllerWait': {
    post: operations['_api_MaaControllerWait']
  }
  '/api/MaaCreate': {
    post: operations['_api_MaaCreate']
  }
  '/api/MaaCreateImageBuffer': {
    post: operations['_api_MaaCreateImageBuffer']
  }
  '/api/MaaDbgControllerCreate': {
    post: operations['_api_MaaDbgControllerCreate']
  }
  '/api/MaaDestroy': {
    post: operations['_api_MaaDestroy']
  }
  '/api/MaaDestroyImageBuffer': {
    post: operations['_api_MaaDestroyImageBuffer']
  }
  '/api/MaaGetController': {
    post: operations['_api_MaaGetController']
  }
  '/api/MaaGetImageEncoded': {
    post: operations['_api_MaaGetImageEncoded']
  }
  '/api/MaaGetImageHeight': {
    post: operations['_api_MaaGetImageHeight']
  }
  '/api/MaaGetImageType': {
    post: operations['_api_MaaGetImageType']
  }
  '/api/MaaGetImageWidth': {
    post: operations['_api_MaaGetImageWidth']
  }
  '/api/MaaGetResource': {
    post: operations['_api_MaaGetResource']
  }
  '/api/MaaInited': {
    post: operations['_api_MaaInited']
  }
  '/api/MaaIsImageEmpty': {
    post: operations['_api_MaaIsImageEmpty']
  }
  '/api/MaaPostStop': {
    post: operations['_api_MaaPostStop']
  }
  '/api/MaaPostTask': {
    post: operations['_api_MaaPostTask']
  }
  '/api/MaaRegisterCustomAction': {
    post: operations['_api_MaaRegisterCustomAction']
  }
  '/api/MaaRegisterCustomRecognizer': {
    post: operations['_api_MaaRegisterCustomRecognizer']
  }
  '/api/MaaResourceClear': {
    post: operations['_api_MaaResourceClear']
  }
  '/api/MaaResourceCreate': {
    post: operations['_api_MaaResourceCreate']
  }
  '/api/MaaResourceDestroy': {
    post: operations['_api_MaaResourceDestroy']
  }
  '/api/MaaResourceGetHash': {
    post: operations['_api_MaaResourceGetHash']
  }
  '/api/MaaResourceGetTaskList': {
    post: operations['_api_MaaResourceGetTaskList']
  }
  '/api/MaaResourceLoaded': {
    post: operations['_api_MaaResourceLoaded']
  }
  '/api/MaaResourcePostPath': {
    post: operations['_api_MaaResourcePostPath']
  }
  '/api/MaaResourceStatus': {
    post: operations['_api_MaaResourceStatus']
  }
  '/api/MaaResourceWait': {
    post: operations['_api_MaaResourceWait']
  }
  '/api/MaaRunning': {
    post: operations['_api_MaaRunning']
  }
  '/api/MaaSetGlobalOptionBoolean': {
    post: operations['_api_MaaSetGlobalOptionBoolean']
  }
  '/api/MaaSetGlobalOptionInteger': {
    post: operations['_api_MaaSetGlobalOptionInteger']
  }
  '/api/MaaSetGlobalOptionString': {
    post: operations['_api_MaaSetGlobalOptionString']
  }
  '/api/MaaSetImageEncoded': {
    post: operations['_api_MaaSetImageEncoded']
  }
  '/api/MaaSetTaskParam': {
    post: operations['_api_MaaSetTaskParam']
  }
  '/api/MaaTaskStatus': {
    post: operations['_api_MaaTaskStatus']
  }
  '/api/MaaThriftControllerCreate': {
    post: operations['_api_MaaThriftControllerCreate']
  }
  '/api/MaaToolkitFindWindow': {
    post: operations['_api_MaaToolkitFindWindow']
  }
  '/api/MaaToolkitGetCursorWindow': {
    post: operations['_api_MaaToolkitGetCursorWindow']
  }
  '/api/MaaToolkitGetDesktopWindow': {
    post: operations['_api_MaaToolkitGetDesktopWindow']
  }
  '/api/MaaToolkitGetDeviceAdbConfig': {
    post: operations['_api_MaaToolkitGetDeviceAdbConfig']
  }
  '/api/MaaToolkitGetDeviceAdbControllerType': {
    post: operations['_api_MaaToolkitGetDeviceAdbControllerType']
  }
  '/api/MaaToolkitGetDeviceAdbPath': {
    post: operations['_api_MaaToolkitGetDeviceAdbPath']
  }
  '/api/MaaToolkitGetDeviceAdbSerial': {
    post: operations['_api_MaaToolkitGetDeviceAdbSerial']
  }
  '/api/MaaToolkitGetDeviceCount': {
    post: operations['_api_MaaToolkitGetDeviceCount']
  }
  '/api/MaaToolkitGetDeviceName': {
    post: operations['_api_MaaToolkitGetDeviceName']
  }
  '/api/MaaToolkitGetForegroundWindow': {
    post: operations['_api_MaaToolkitGetForegroundWindow']
  }
  '/api/MaaToolkitGetWindow': {
    post: operations['_api_MaaToolkitGetWindow']
  }
  '/api/MaaToolkitInitOptionConfig': {
    post: operations['_api_MaaToolkitInitOptionConfig']
  }
  '/api/MaaToolkitIsFindDeviceCompleted': {
    post: operations['_api_MaaToolkitIsFindDeviceCompleted']
  }
  '/api/MaaToolkitPostFindDevice': {
    post: operations['_api_MaaToolkitPostFindDevice']
  }
  '/api/MaaToolkitPostFindDeviceWithAdb': {
    post: operations['_api_MaaToolkitPostFindDeviceWithAdb']
  }
  '/api/MaaToolkitRegisterCustomActionExecutor': {
    post: operations['_api_MaaToolkitRegisterCustomActionExecutor']
  }
  '/api/MaaToolkitRegisterCustomRecognizerExecutor': {
    post: operations['_api_MaaToolkitRegisterCustomRecognizerExecutor']
  }
  '/api/MaaToolkitSearchWindow': {
    post: operations['_api_MaaToolkitSearchWindow']
  }
  '/api/MaaToolkitUnregisterCustomActionExecutor': {
    post: operations['_api_MaaToolkitUnregisterCustomActionExecutor']
  }
  '/api/MaaToolkitUnregisterCustomRecognizerExecutor': {
    post: operations['_api_MaaToolkitUnregisterCustomRecognizerExecutor']
  }
  '/api/MaaToolkitWaitForFindDeviceToComplete': {
    post: operations['_api_MaaToolkitWaitForFindDeviceToComplete']
  }
  '/api/MaaUnregisterCustomAction': {
    post: operations['_api_MaaUnregisterCustomAction']
  }
  '/api/MaaUnregisterCustomRecognizer': {
    post: operations['_api_MaaUnregisterCustomRecognizer']
  }
  '/api/MaaVersion': {
    post: operations['_api_MaaVersion']
  }
  '/api/MaaWaitTask': {
    post: operations['_api_MaaWaitTask']
  }
  '/api/MaaWin32ControllerCreate': {
    post: operations['_api_MaaWin32ControllerCreate']
  }
  '/callback/CustomActionRun/dump': {
    post: operations['_callback_CustomActionRun_dump']
  }
  '/callback/CustomActionRun/free': {
    post: operations['_callback_CustomActionRun_free']
  }
  '/callback/CustomActionRun/new': {
    post: operations['_callback_CustomActionRun_new']
  }
  '/callback/CustomActionRun/query': {
    post: operations['_callback_CustomActionRun_query']
  }
  '/callback/CustomActionRun/req': {
    post: operations['_callback_CustomActionRun_req']
  }
  '/callback/CustomActionRun/res': {
    post: operations['_callback_CustomActionRun_res']
  }
  '/callback/CustomActionStop/dump': {
    post: operations['_callback_CustomActionStop_dump']
  }
  '/callback/CustomActionStop/free': {
    post: operations['_callback_CustomActionStop_free']
  }
  '/callback/CustomActionStop/new': {
    post: operations['_callback_CustomActionStop_new']
  }
  '/callback/CustomActionStop/query': {
    post: operations['_callback_CustomActionStop_query']
  }
  '/callback/CustomActionStop/req': {
    post: operations['_callback_CustomActionStop_req']
  }
  '/callback/CustomActionStop/res': {
    post: operations['_callback_CustomActionStop_res']
  }
  '/callback/CustomRecognizerAnalyze/dump': {
    post: operations['_callback_CustomRecognizerAnalyze_dump']
  }
  '/callback/CustomRecognizerAnalyze/free': {
    post: operations['_callback_CustomRecognizerAnalyze_free']
  }
  '/callback/CustomRecognizerAnalyze/new': {
    post: operations['_callback_CustomRecognizerAnalyze_new']
  }
  '/callback/CustomRecognizerAnalyze/query': {
    post: operations['_callback_CustomRecognizerAnalyze_query']
  }
  '/callback/CustomRecognizerAnalyze/req': {
    post: operations['_callback_CustomRecognizerAnalyze_req']
  }
  '/callback/CustomRecognizerAnalyze/res': {
    post: operations['_callback_CustomRecognizerAnalyze_res']
  }
  '/callback/MaaAPICallback/dump': {
    post: operations['_callback_MaaAPICallback_dump']
  }
  '/callback/MaaAPICallback/free': {
    post: operations['_callback_MaaAPICallback_free']
  }
  '/callback/MaaAPICallback/new': {
    post: operations['_callback_MaaAPICallback_new']
  }
  '/callback/MaaAPICallback/query': {
    post: operations['_callback_MaaAPICallback_query']
  }
  '/callback/MaaAPICallback/req': {
    post: operations['_callback_MaaAPICallback_req']
  }
  '/callback/MaaAPICallback/res': {
    post: operations['_callback_MaaAPICallback_res']
  }
  '/handle/MaaControllerAPI/dump': {
    post: operations['_handle_MaaControllerAPI_dump']
  }
  '/handle/MaaImageBuffer/dump': {
    post: operations['_handle_MaaImageBuffer_dump']
  }
  '/handle/MaaInstanceAPI/dump': {
    post: operations['_handle_MaaInstanceAPI_dump']
  }
  '/handle/MaaResourceAPI/dump': {
    post: operations['_handle_MaaResourceAPI_dump']
  }
  '/handle/MaaSyncContextAPI/dump': {
    post: operations['_handle_MaaSyncContextAPI_dump']
  }
  '/help': {
    post: operations['_help']
  }
}

export type webhooks = Record<string, never>

export type components = Record<string, never>

export type $defs = Record<string, never>

export type external = Record<string, never>

export interface operations {
  _api_MaaAdbControllerCreateV2: {
    requestBody?: {
      content: {
        'application/json': {
          adb_path: string
          address: string
          agent_path: string
          callback: string
          config: string
          type: number
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              /** MaaControllerAPI */
              return: string
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaBindController: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaControllerAPI */
          ctrl: string
          /** MaaInstanceAPI */
          inst: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaBindResource: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaInstanceAPI */
          inst: string
          /** MaaResourceAPI */
          res: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaClearCustomAction: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaInstanceAPI */
          inst: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaClearCustomRecognizer: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaInstanceAPI */
          inst: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaClearImage: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaImageBuffer */
          handle: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaControllerConnected: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaControllerAPI */
          ctrl: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaControllerDestroy: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaControllerAPI */
          ctrl: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: Record<string, never>
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaControllerGetImage: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaImageBuffer */
          buffer: string
          /** MaaControllerAPI */
          ctrl: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaControllerGetUUID: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaControllerAPI */
          ctrl: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              buffer: string
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaControllerPostClick: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaControllerAPI */
          ctrl: string
          x: number
          y: number
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaControllerPostConnection: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaControllerAPI */
          ctrl: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaControllerPostInputText: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaControllerAPI */
          ctrl: string
          text: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaControllerPostPressKey: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaControllerAPI */
          ctrl: string
          keycode: number
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaControllerPostScreencap: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaControllerAPI */
          ctrl: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaControllerPostSwipe: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaControllerAPI */
          ctrl: string
          duration: number
          x1: number
          x2: number
          y1: number
          y2: number
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaControllerPostTouchDown: {
    requestBody?: {
      content: {
        'application/json': {
          contact: number
          /** MaaControllerAPI */
          ctrl: string
          pressure: number
          x: number
          y: number
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaControllerPostTouchMove: {
    requestBody?: {
      content: {
        'application/json': {
          contact: number
          /** MaaControllerAPI */
          ctrl: string
          pressure: number
          x: number
          y: number
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaControllerPostTouchUp: {
    requestBody?: {
      content: {
        'application/json': {
          contact: number
          /** MaaControllerAPI */
          ctrl: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaControllerSetOptionBoolean: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaControllerAPI */
          ctrl: string
          key: number
          value: boolean
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaControllerSetOptionInteger: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaControllerAPI */
          ctrl: string
          key: number
          value: number
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaControllerSetOptionString: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaControllerAPI */
          ctrl: string
          key: number
          value: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaControllerStatus: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaControllerAPI */
          ctrl: string
          id: number
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaControllerWait: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaControllerAPI */
          ctrl: string
          id: number
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaCreate: {
    requestBody?: {
      content: {
        'application/json': {
          callback: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              /** MaaInstanceAPI */
              return: string
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaCreateImageBuffer: {
    requestBody?: {
      content: {
        'application/json': Record<string, never>
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              /** MaaImageBuffer */
              return: string
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaDbgControllerCreate: {
    requestBody?: {
      content: {
        'application/json': {
          callback: string
          config: string
          read_path: string
          type: number
          write_path: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              /** MaaControllerAPI */
              return: string
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaDestroy: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaInstanceAPI */
          inst: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: Record<string, never>
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaDestroyImageBuffer: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaImageBuffer */
          handle: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: Record<string, never>
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaGetController: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaInstanceAPI */
          inst: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              /** MaaControllerAPI */
              return: string
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaGetImageEncoded: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaImageBuffer */
          handle: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: string
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaGetImageHeight: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaImageBuffer */
          handle: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaGetImageType: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaImageBuffer */
          handle: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaGetImageWidth: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaImageBuffer */
          handle: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaGetResource: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaInstanceAPI */
          inst: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              /** MaaResourceAPI */
              return: string
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaInited: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaInstanceAPI */
          inst: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaIsImageEmpty: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaImageBuffer */
          handle: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaPostStop: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaInstanceAPI */
          inst: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaPostTask: {
    requestBody?: {
      content: {
        'application/json': {
          entry: string
          /** MaaInstanceAPI */
          inst: string
          param: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaRegisterCustomAction: {
    requestBody?: {
      content: {
        'application/json': {
          action: {
            run: string
            stop: string
          }
          /** MaaInstanceAPI */
          inst: string
          name: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaRegisterCustomRecognizer: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaInstanceAPI */
          inst: string
          name: string
          recognizer: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaResourceClear: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaResourceAPI */
          res: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaResourceCreate: {
    requestBody?: {
      content: {
        'application/json': {
          callback: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              /** MaaResourceAPI */
              return: string
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaResourceDestroy: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaResourceAPI */
          res: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: Record<string, never>
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaResourceGetHash: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaResourceAPI */
          res: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              buffer: string
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaResourceGetTaskList: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaResourceAPI */
          res: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              buffer: string
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaResourceLoaded: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaResourceAPI */
          res: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaResourcePostPath: {
    requestBody?: {
      content: {
        'application/json': {
          path: string
          /** MaaResourceAPI */
          res: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaResourceStatus: {
    requestBody?: {
      content: {
        'application/json': {
          id: number
          /** MaaResourceAPI */
          res: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaResourceWait: {
    requestBody?: {
      content: {
        'application/json': {
          id: number
          /** MaaResourceAPI */
          res: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaRunning: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaInstanceAPI */
          inst: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaSetGlobalOptionBoolean: {
    requestBody?: {
      content: {
        'application/json': {
          key: number
          value: boolean
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaSetGlobalOptionInteger: {
    requestBody?: {
      content: {
        'application/json': {
          key: number
          value: number
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaSetGlobalOptionString: {
    requestBody?: {
      content: {
        'application/json': {
          key: number
          value: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaSetImageEncoded: {
    requestBody?: {
      content: {
        'application/json': {
          data: string
          /** MaaImageBuffer */
          handle: string
          size: number
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaSetTaskParam: {
    requestBody?: {
      content: {
        'application/json': {
          id: number
          /** MaaInstanceAPI */
          inst: string
          param: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaTaskStatus: {
    requestBody?: {
      content: {
        'application/json': {
          id: number
          /** MaaInstanceAPI */
          inst: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaThriftControllerCreate: {
    requestBody?: {
      content: {
        'application/json': {
          callback: string
          config: string
          host: string
          port: number
          type: number
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              /** MaaControllerAPI */
              return: string
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaToolkitFindWindow: {
    requestBody?: {
      content: {
        'application/json': {
          class_name: string
          window_name: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaToolkitGetCursorWindow: {
    requestBody?: {
      content: {
        'application/json': Record<string, never>
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: string
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaToolkitGetDesktopWindow: {
    requestBody?: {
      content: {
        'application/json': Record<string, never>
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: string
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaToolkitGetDeviceAdbConfig: {
    requestBody?: {
      content: {
        'application/json': {
          index: number
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: string
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaToolkitGetDeviceAdbControllerType: {
    requestBody?: {
      content: {
        'application/json': {
          index: number
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaToolkitGetDeviceAdbPath: {
    requestBody?: {
      content: {
        'application/json': {
          index: number
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: string
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaToolkitGetDeviceAdbSerial: {
    requestBody?: {
      content: {
        'application/json': {
          index: number
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: string
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaToolkitGetDeviceCount: {
    requestBody?: {
      content: {
        'application/json': Record<string, never>
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaToolkitGetDeviceName: {
    requestBody?: {
      content: {
        'application/json': {
          index: number
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: string
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaToolkitGetForegroundWindow: {
    requestBody?: {
      content: {
        'application/json': Record<string, never>
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: string
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaToolkitGetWindow: {
    requestBody?: {
      content: {
        'application/json': {
          index: number
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: string
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaToolkitInitOptionConfig: {
    requestBody?: {
      content: {
        'application/json': {
          default_json: string
          user_path: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaToolkitIsFindDeviceCompleted: {
    requestBody?: {
      content: {
        'application/json': Record<string, never>
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaToolkitPostFindDevice: {
    requestBody?: {
      content: {
        'application/json': Record<string, never>
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaToolkitPostFindDeviceWithAdb: {
    requestBody?: {
      content: {
        'application/json': {
          adb_path: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaToolkitRegisterCustomActionExecutor: {
    requestBody?: {
      content: {
        'application/json': {
          action_exec_param_json: string
          action_exec_path: string
          action_name: string
          /** MaaInstanceAPI */
          handle: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaToolkitRegisterCustomRecognizerExecutor: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaInstanceAPI */
          handle: string
          recognizer_exec_param_json: string
          recognizer_exec_path: string
          recognizer_name: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaToolkitSearchWindow: {
    requestBody?: {
      content: {
        'application/json': {
          class_name: string
          window_name: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaToolkitUnregisterCustomActionExecutor: {
    requestBody?: {
      content: {
        'application/json': {
          action_name: string
          /** MaaInstanceAPI */
          handle: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaToolkitUnregisterCustomRecognizerExecutor: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaInstanceAPI */
          handle: string
          recognizer_name: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaToolkitWaitForFindDeviceToComplete: {
    requestBody?: {
      content: {
        'application/json': Record<string, never>
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaUnregisterCustomAction: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaInstanceAPI */
          inst: string
          name: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaUnregisterCustomRecognizer: {
    requestBody?: {
      content: {
        'application/json': {
          /** MaaInstanceAPI */
          inst: string
          name: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaVersion: {
    requestBody?: {
      content: {
        'application/json': Record<string, never>
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: string
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaWaitTask: {
    requestBody?: {
      content: {
        'application/json': {
          id: number
          /** MaaInstanceAPI */
          inst: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              return: number
            }
            success: boolean
          }
        }
      }
    }
  }
  _api_MaaWin32ControllerCreate: {
    requestBody?: {
      content: {
        'application/json': {
          callback: string
          hWnd: string
          type: number
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              /** MaaControllerAPI */
              return: string
            }
            success: boolean
          }
        }
      }
    }
  }
  _callback_CustomActionRun_dump: {
    requestBody?: {
      content: {
        'application/json': unknown
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              ids: string[]
            }
            success: boolean
          }
        }
      }
    }
  }
  _callback_CustomActionRun_free: {
    requestBody?: {
      content: {
        'application/json': {
          id: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: unknown
            success: boolean
          }
        }
      }
    }
  }
  _callback_CustomActionRun_new: {
    requestBody?: {
      content: {
        'application/json': unknown
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              id: string
            }
            success: boolean
          }
        }
      }
    }
  }
  _callback_CustomActionRun_query: {
    requestBody?: {
      content: {
        'application/json': {
          id: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              ids: string[]
            }
            success: boolean
          }
        }
      }
    }
  }
  _callback_CustomActionRun_req: {
    requestBody?: {
      content: {
        'application/json': {
          cid: string
          id: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              cur_box: {
                height: number
                width: number
                x: number
                y: number
              }
              cur_rec_detail: string
              custom_action_param: string
              /** MaaSyncContextAPI */
              sync_context: string
              task_name: string
            }
            success: boolean
          }
        }
      }
    }
  }
  _callback_CustomActionRun_res: {
    requestBody?: {
      content: {
        'application/json': {
          cid: string
          id: string
          ret: {
            return: number
          }
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: unknown
            success: boolean
          }
        }
      }
    }
  }
  _callback_CustomActionStop_dump: {
    requestBody?: {
      content: {
        'application/json': unknown
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              ids: string[]
            }
            success: boolean
          }
        }
      }
    }
  }
  _callback_CustomActionStop_free: {
    requestBody?: {
      content: {
        'application/json': {
          id: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: unknown
            success: boolean
          }
        }
      }
    }
  }
  _callback_CustomActionStop_new: {
    requestBody?: {
      content: {
        'application/json': unknown
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              id: string
            }
            success: boolean
          }
        }
      }
    }
  }
  _callback_CustomActionStop_query: {
    requestBody?: {
      content: {
        'application/json': {
          id: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              ids: string[]
            }
            success: boolean
          }
        }
      }
    }
  }
  _callback_CustomActionStop_req: {
    requestBody?: {
      content: {
        'application/json': {
          cid: string
          id: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: Record<string, never>
            success: boolean
          }
        }
      }
    }
  }
  _callback_CustomActionStop_res: {
    requestBody?: {
      content: {
        'application/json': {
          cid: string
          id: string
          ret: Record<string, never>
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: unknown
            success: boolean
          }
        }
      }
    }
  }
  _callback_CustomRecognizerAnalyze_dump: {
    requestBody?: {
      content: {
        'application/json': unknown
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              ids: string[]
            }
            success: boolean
          }
        }
      }
    }
  }
  _callback_CustomRecognizerAnalyze_free: {
    requestBody?: {
      content: {
        'application/json': {
          id: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: unknown
            success: boolean
          }
        }
      }
    }
  }
  _callback_CustomRecognizerAnalyze_new: {
    requestBody?: {
      content: {
        'application/json': unknown
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              id: string
            }
            success: boolean
          }
        }
      }
    }
  }
  _callback_CustomRecognizerAnalyze_query: {
    requestBody?: {
      content: {
        'application/json': {
          id: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              ids: string[]
            }
            success: boolean
          }
        }
      }
    }
  }
  _callback_CustomRecognizerAnalyze_req: {
    requestBody?: {
      content: {
        'application/json': {
          cid: string
          id: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              custom_recognition_param: string
              /** MaaImageBuffer */
              image: string
              /** MaaSyncContextAPI */
              sync_context: string
              task_name: string
            }
            success: boolean
          }
        }
      }
    }
  }
  _callback_CustomRecognizerAnalyze_res: {
    requestBody?: {
      content: {
        'application/json': {
          cid: string
          id: string
          ret: {
            out_box: {
              height: number
              width: number
              x: number
              y: number
            }
            out_detail: string
            return: number
          }
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: unknown
            success: boolean
          }
        }
      }
    }
  }
  _callback_MaaAPICallback_dump: {
    requestBody?: {
      content: {
        'application/json': unknown
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              ids: string[]
            }
            success: boolean
          }
        }
      }
    }
  }
  _callback_MaaAPICallback_free: {
    requestBody?: {
      content: {
        'application/json': {
          id: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: unknown
            success: boolean
          }
        }
      }
    }
  }
  _callback_MaaAPICallback_new: {
    requestBody?: {
      content: {
        'application/json': unknown
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              id: string
            }
            success: boolean
          }
        }
      }
    }
  }
  _callback_MaaAPICallback_query: {
    requestBody?: {
      content: {
        'application/json': {
          id: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              ids: string[]
            }
            success: boolean
          }
        }
      }
    }
  }
  _callback_MaaAPICallback_req: {
    requestBody?: {
      content: {
        'application/json': {
          cid: string
          id: string
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              details_json: string
              msg: string
            }
            success: boolean
          }
        }
      }
    }
  }
  _callback_MaaAPICallback_res: {
    requestBody?: {
      content: {
        'application/json': {
          cid: string
          id: string
          ret: Record<string, never>
        }
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: unknown
            success: boolean
          }
        }
      }
    }
  }
  _handle_MaaControllerAPI_dump: {
    requestBody?: {
      content: {
        'application/json': unknown
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              ids: string[]
            }
            success: boolean
          }
        }
      }
    }
  }
  _handle_MaaImageBuffer_dump: {
    requestBody?: {
      content: {
        'application/json': unknown
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              ids: string[]
            }
            success: boolean
          }
        }
      }
    }
  }
  _handle_MaaInstanceAPI_dump: {
    requestBody?: {
      content: {
        'application/json': unknown
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              ids: string[]
            }
            success: boolean
          }
        }
      }
    }
  }
  _handle_MaaResourceAPI_dump: {
    requestBody?: {
      content: {
        'application/json': unknown
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              ids: string[]
            }
            success: boolean
          }
        }
      }
    }
  }
  _handle_MaaSyncContextAPI_dump: {
    requestBody?: {
      content: {
        'application/json': unknown
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            data?: {
              ids: string[]
            }
            success: boolean
          }
        }
      }
    }
  }
  _help: {
    requestBody?: {
      content: {
        'application/json': unknown
      }
    }
    responses: {
      200: {
        content: {
          'application/json': Record<string, never>
        }
      }
    }
  }
}
