/**
 * This file was auto-generated by @liangskyli/openapi-gen-ts.
 * Do not make direct changes to the file.
 */

/** OneOf type helpers */
type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never }
type XOR<T, U> = T | U extends object ? (Without<T, U> & U) | (Without<U, T> & T) : T | U
type OneOf<T extends any[]> = T extends [infer Only]
  ? Only
  : T extends [infer A, infer B, ...infer Rest]
    ? OneOf<[XOR<A, B>, ...Rest]>
    : never

export interface paths {
  '/api/MaaAdbControllerCreate': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            adb_path: string
            address: string
            /** MaaAPICallback */
            callback: string
            config: string
            type: number
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    /** MaaControllerAPI */
                    return: string
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaAdbControllerCreateV2': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            adb_path: string
            address: string
            agent_path: string
            /** MaaAPICallback */
            callback: string
            config: string
            type: number
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    /** MaaControllerAPI */
                    return: string
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaBindController': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaControllerAPI */
            ctrl: string
            /** MaaInstanceAPI */
            inst: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaBindResource': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaInstanceAPI */
            inst: string
            /** MaaResourceAPI */
            res: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaClearCustomAction': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaInstanceAPI */
            inst: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaClearCustomRecognizer': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaInstanceAPI */
            inst: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaClearImage': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaImageBuffer */
            handle: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaControllerConnected': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaControllerAPI */
            ctrl: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaControllerDestroy': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaControllerAPI */
            ctrl: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: null
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaControllerGetImage': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaImageBuffer */
            buffer: string
            /** MaaControllerAPI */
            ctrl: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaControllerGetUUID': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaControllerAPI */
            ctrl: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    buffer: string
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaControllerPostClick': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaControllerAPI */
            ctrl: string
            x: number
            y: number
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaControllerPostConnection': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaControllerAPI */
            ctrl: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaControllerPostInputText': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaControllerAPI */
            ctrl: string
            text: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaControllerPostPressKey': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaControllerAPI */
            ctrl: string
            keycode: number
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaControllerPostScreencap': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaControllerAPI */
            ctrl: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaControllerPostSwipe': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaControllerAPI */
            ctrl: string
            duration: number
            x1: number
            x2: number
            y1: number
            y2: number
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaControllerPostTouchDown': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            contact: number
            /** MaaControllerAPI */
            ctrl: string
            pressure: number
            x: number
            y: number
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaControllerPostTouchMove': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            contact: number
            /** MaaControllerAPI */
            ctrl: string
            pressure: number
            x: number
            y: number
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaControllerPostTouchUp': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            contact: number
            /** MaaControllerAPI */
            ctrl: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaControllerSetOptionBoolean': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaControllerAPI */
            ctrl: string
            key: number
            value: boolean
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaControllerSetOptionInteger': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaControllerAPI */
            ctrl: string
            key: number
            value: number
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaControllerSetOptionString': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaControllerAPI */
            ctrl: string
            key: number
            value: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaControllerStatus': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaControllerAPI */
            ctrl: string
            id: number
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaControllerWait': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaControllerAPI */
            ctrl: string
            id: number
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaCreate': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaAPICallback */
            callback: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    /** MaaInstanceAPI */
                    return: string
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaCreateImageBuffer': {
    post: {
      requestBody?: {
        content: {
          'application/json': unknown
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    /** MaaImageBuffer */
                    return: string
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaDbgControllerCreate': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaAPICallback */
            callback: string
            config: string
            read_path: string
            type: number
            write_path: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    /** MaaControllerAPI */
                    return: string
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaDestroy': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaInstanceAPI */
            inst: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: null
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaDestroyImageBuffer': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaImageBuffer */
            handle: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: null
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaGetController': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaInstanceAPI */
            inst: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    /** MaaControllerAPI */
                    return: string
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaGetImageEncoded': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaImageBuffer */
            handle: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: string
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaGetImageHeight': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaImageBuffer */
            handle: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaGetImageType': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaImageBuffer */
            handle: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaGetImageWidth': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaImageBuffer */
            handle: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaGetResource': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaInstanceAPI */
            inst: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    /** MaaResourceAPI */
                    return: string
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaInited': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaInstanceAPI */
            inst: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaIsImageEmpty': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaImageBuffer */
            handle: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaPostStop': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaInstanceAPI */
            inst: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaPostTask': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            entry: string
            /** MaaInstanceAPI */
            inst: string
            param: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaResourceCreate': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaAPICallback */
            callback: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    /** MaaResourceAPI */
                    return: string
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaResourceDestroy': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaResourceAPI */
            res: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: null
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaResourceGetHash': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaResourceAPI */
            res: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    buffer: string
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaResourceGetTaskList': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaResourceAPI */
            res: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    buffer: string
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaResourceLoaded': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaResourceAPI */
            res: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaResourcePostPath': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            path: string
            /** MaaResourceAPI */
            res: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaResourceStatus': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            id: number
            /** MaaResourceAPI */
            res: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaResourceWait': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            id: number
            /** MaaResourceAPI */
            res: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaSetGlobalOptionBoolean': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            key: number
            value: boolean
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaSetGlobalOptionInteger': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            key: number
            value: number
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaSetGlobalOptionString': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            key: number
            value: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaSetImageEncoded': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            data: string
            /** MaaImageBuffer */
            handle: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaSetTaskParam': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            id: number
            /** MaaInstanceAPI */
            inst: string
            param: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaStop': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaInstanceAPI */
            inst: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaTaskAllFinished': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaInstanceAPI */
            inst: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaTaskStatus': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            id: number
            /** MaaInstanceAPI */
            inst: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaThriftControllerCreate': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaAPICallback */
            callback: string
            config: string
            host: string
            port: number
            type: number
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    /** MaaControllerAPI */
                    return: string
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaToolkitFindDevice': {
    post: {
      requestBody?: {
        content: {
          'application/json': unknown
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaToolkitFindDeviceWithAdb': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            adb_path: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaToolkitFindWindow': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            class_name: string
            window_name: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaToolkitGetCursorWindow': {
    post: {
      requestBody?: {
        content: {
          'application/json': unknown
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaToolkitGetDesktopWindow': {
    post: {
      requestBody?: {
        content: {
          'application/json': unknown
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaToolkitGetDeviceAdbConfig': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            index: number
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: string
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaToolkitGetDeviceAdbControllerType': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            index: number
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaToolkitGetDeviceAdbPath': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            index: number
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: string
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaToolkitGetDeviceAdbSerial': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            index: number
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: string
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaToolkitGetDeviceCount': {
    post: {
      requestBody?: {
        content: {
          'application/json': unknown
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaToolkitGetDeviceName': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            index: number
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: string
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaToolkitGetForegroundWindow': {
    post: {
      requestBody?: {
        content: {
          'application/json': unknown
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaToolkitGetWindow': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            index: number
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaToolkitInit': {
    post: {
      requestBody?: {
        content: {
          'application/json': unknown
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaToolkitIsFindDeviceCompleted': {
    post: {
      requestBody?: {
        content: {
          'application/json': unknown
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaToolkitPostFindDevice': {
    post: {
      requestBody?: {
        content: {
          'application/json': unknown
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaToolkitPostFindDeviceWithAdb': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            adb_path: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaToolkitRegisterCustomActionExecutor': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            action_exec_param_json: string
            action_exec_path: string
            action_name: string
            /** MaaInstanceAPI */
            handle: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaToolkitRegisterCustomRecognizerExecutor': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaInstanceAPI */
            handle: string
            recognizer_exec_param_json: string
            recognizer_exec_path: string
            recognizer_name: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaToolkitSearchWindow': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            class_name: string
            window_name: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaToolkitUninit': {
    post: {
      requestBody?: {
        content: {
          'application/json': unknown
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaToolkitUnregisterCustomActionExecutor': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            action_name: string
            /** MaaInstanceAPI */
            handle: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaToolkitUnregisterCustomRecognizerExecutor': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaInstanceAPI */
            handle: string
            recognizer_name: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaToolkitWaitForFindDeviceToComplete': {
    post: {
      requestBody?: {
        content: {
          'application/json': unknown
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaVersion': {
    post: {
      requestBody?: {
        content: {
          'application/json': unknown
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: string
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaWaitTask': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            id: number
            /** MaaInstanceAPI */
            inst: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    return: number
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/api/MaaWin32ControllerCreate': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            /** MaaAPICallback */
            callback: string
            hWnd: number
            type: number
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    /** MaaControllerAPI */
                    return: string
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/callback/MaaAPICallback/add': {
    post: {
      requestBody?: {
        content: {
          'application/json': unknown
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    id: string
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/callback/MaaAPICallback/del': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            id: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: unknown
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/callback/MaaAPICallback/dump': {
    post: {
      requestBody?: {
        content: {
          'application/json': unknown
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    ids: string[]
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/callback/MaaAPICallback/pull': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            id: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    ids: string[]
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/callback/MaaAPICallback/request': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            cid: string
            id: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    details_json: string
                    msg: string
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/callback/MaaAPICallback/response': {
    post: {
      requestBody?: {
        content: {
          'application/json': {
            cid: string
            id: string
          }
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: unknown
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/opaque/MaaControllerAPI': {
    post: {
      requestBody?: {
        content: {
          'application/json': unknown
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    [key: string]: {
                      pointer: string
                    }
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/opaque/MaaImageBuffer': {
    post: {
      requestBody?: {
        content: {
          'application/json': unknown
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    [key: string]: {
                      pointer: string
                    }
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/opaque/MaaInstanceAPI': {
    post: {
      requestBody?: {
        content: {
          'application/json': unknown
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    [key: string]: {
                      pointer: string
                    }
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
  '/opaque/MaaResourceAPI': {
    post: {
      requestBody?: {
        content: {
          'application/json': unknown
        }
      }
      responses: {
        200: {
          content: {
            'application/json': OneOf<
              [
                {
                  data: {
                    [key: string]: {
                      pointer: string
                    }
                  }
                },
                {
                  error: string
                }
              ]
            >
          }
        }
      }
    }
  }
}

export type webhooks = Record<string, never>

export type components = Record<string, never>

export type $defs = Record<string, never>

export type external = Record<string, never>

export type operations = Record<string, never>
